language: android
sudo: true

jdk:
  - oraclejdk8




android:
  components:
    # Those two lines allow us to use any build tools version.
    - tools
    - platform-tools

    - build-tools-25.0.2
    - android-15

    - extra-google-m2repository
    - extra-android-m2repository


before_install:
  - mkdir -p $HOME/.gradle/caches/
  - mkdir -p $HOME/.gradle/wrapper/


before_script:
  - sudo service postgresql stop || true
  - sudo service mysql stop || true
  - sudo service memcached stop || true
  - sudo service bootlogd stop || true
  - sudo service elasticsearch stop || true
  - sudo service mongodb stop || true
  - sudo service neo4j stop || true
  - sudo service cassandra stop || true
  - sudo service riak stop || true
  - sudo service rsync stop || true
  - sudo service x11-common stop || true

  
env:
  # Only compile and build basic jars
  - TARGET="assemble"
  - TARGET=":jsettlers.main.android:build"

  # Run single test targets
  - TARGET=":jsettlers.logic:unitTest"
  - TARGET=":jsettlers.common:test"
  - TARGET=":jsettlers.network:test --info"
  - TARGET=":jsettlers.logic:aiDifficultiesIT"
  - TARGET=":jsettlers.logic:autoReplayIT"
  - TARGET=":jsettlers.logic:replayValidationIT"
  
  - TARGET="release deployToGithub"

  
script: GRADLE_OPTS='-Xmx600m -Dorg.gradle.jvmargs="-Xmx1500m"' ./gradlew $TARGET
