language: android
sudo: true

jdk:
  - oraclejdk8

env:
  global:
     - ANDROID_TARGET=android-15
     - ANDROID_ABI=armeabi-v7a

  matrix:
    # Only compile and build basic jars
    - NO_EMULATOR=true TARGET="assemble"
    - NO_EMULATOR=true TARGET=":jsettlers.main.android:build"

    # Run emulator test to ensure it runs on Android
    - NO_EMULATOR=false TARGET=":jsettlers.main.android:connectedAndroidTest"

    # Run single test targets
    - NO_EMULATOR=true TARGET=":jsettlers.logic:unitTest"
    - NO_EMULATOR=true TARGET=":jsettlers.common:test"
    - NO_EMULATOR=true TARGET=":jsettlers.network:test --info"
    - NO_EMULATOR=true TARGET=":jsettlers.logic:aiDifficultiesIT"
    - NO_EMULATOR=true TARGET=":jsettlers.logic:autoReplayIT"
    - NO_EMULATOR=true TARGET=":jsettlers.logic:replayValidationIT"

    # Deploy to GitHub
    - NO_EMULATOR=true TARGET="release deployToGithub"


android:
  components:
    # Those two lines allow us to use any build tools version.
    - tools
    - platform-tools

    - build-tools-25.0.2
    - $ANDROID_TARGET

    - extra-google-m2repository
    - extra-android-m2repository

    - sys-img-$ANDROID_ABI-$ANDROID_TARGET


before_install:
  - mkdir -p $HOME/.gradle/caches/
  - mkdir -p $HOME/.gradle/wrapper/


before_script:
  - sudo service postgresql stop || true
  - sudo service mysql stop || true
  - sudo service memcached stop || true
  - sudo service bootlogd stop || true
  - sudo service elasticsearch stop || true
  - sudo service mongodb stop || true
  - sudo service neo4j stop || true
  - sudo service cassandra stop || true
  - sudo service riak stop || true
  - sudo service rsync stop || true
  - sudo service x11-common stop || true
  - $NO_EMULATOR || echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - $NO_EMULATOR || emulator -avd test -no-audio -no-window &
  - $NO_EMULATOR || android-wait-for-emulator
  - $NO_EMULATOR || adb shell input keyevent 82 &


script: GRADLE_OPTS='-Xmx600m -Dorg.gradle.jvmargs="-Xmx1500m"' ./gradlew $TARGET
