name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

- uses: actions/checkout@v2
- uses: actions/setup-java@v1
  with:
    java-version: 1.8
- uses: eskatos/gradle-command-action@v1
  with:
    gradle-version: current
    wrapper-cache-enabled: true
    dependencies-cache-enabled: true
    configuration-cache-enabled: true
    arguments: assemble
- uses: actions/upload-artifact@v2
  with:
    name: Release
    path: app/build/outputs/apk/ourbuildtype/release/app-artifact-*.apk
