name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distribution: [ 'zulu', 'temurin' ]
        java: [ '8', '11', '13', '15', '16' ]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: ${{ matrix.distribution }}
        java-version: ${{ matrix.java }}
        cache: 'gradle'
    - uses: jonasb/android-problem-matchers-action@v1
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: release test
    - uses: actions/upload-artifact@v2
      with:
        name: Release
        path: 'release/*'
